version: '3'
services:
zookeeper:
image: confluentinc/cp-zookeeper:latest
ports:
- 2181:2181
kafka:
image: confluentinc/cp-kafka:latest
depends_on:
- zookeeper
ports:
- 9092:9092
environment:
KAFKA_BROKER_ID: 1
KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
volumes:
- /tmp/kafka:/tmp/kafka
topic:
image: confluentinc/cp-kafka-topics:latest
depends_on:
- kafka
command:
- /bin/sh
- -c
- |
kafka-topics --bootstrap-server kafka:9092 --create --topic my-topic --partitions 3 --replication-factor 1
